intro:
  _target_: streamlit.markdown
  body: "# ğŸ‘‹ Bienvenue dans la boite Ã  outils lÃ©gistique\n\nCette application a Ã©tÃ© dÃ©veloppÃ©e pour simplifier l'analyse et la gestion des textes juridiques franÃ§ais et europÃ©ens. GrÃ¢ce Ã  des modÃ¨les d'IA avancÃ©s, vous pourrez explorer, rÃ©sumer et transposer des textes de loi facilement.\n\n## âš™ï¸ **FonctionnalitÃ©s principales** :\n\nğŸ“œ **Gestion des textes de loi** : Importez des textes lÃ©gislatifs franÃ§ais et europÃ©ens depuis diverses sources (Legifrance, EUR-Lex) et visualisez le contenu de maniÃ¨re claire et organisÃ©e.\n\nğŸ¤– **Analyse assistÃ©e par IA** : Utilisez des modÃ¨les de langage, comme GPT-3.5-turbo et GPT-4, pour analyser et rÃ©sumer des articles de loi complexes.\n\nğŸ› ï¸ **Transposition de textes** : VÃ©rifiez la compatibilitÃ© des articles europÃ©ens avec le droit franÃ§ais et identifiez les modifications lÃ©gislatives nÃ©cessaires.\n\nğŸ“¥ **TÃ©lÃ©chargement de donnÃ©es** : Exportez vos analyses sous divers formats (CSV, JSON, TXT, HTML) pour un usage ultÃ©rieur.\n\n## ğŸš€ Comment dÃ©marrer ?\nğŸ“‚ **SÃ©lectionnez un texte** : Choisissez parmi les textes franÃ§ais ou europÃ©ens existants, ou importez-en de nouveaux.\n\nğŸ”§ **Choisissez l'outil d'analyse** : Selon le type de texte, plusieurs outils s'offrent Ã  vous, comme la projection d'articles ou le rÃ©sumÃ© d'un texte europÃ©en.\nâš¡ **Lancez l'analyse** : Une fois l'outil choisi, l'application analysera automatiquement les articles sÃ©lectionnÃ©s et vous proposera des rÃ©sumÃ©s, des suggestions de transposition ou d'autres analyses pertinentes.\n\nğŸ“Š **TÃ©lÃ©chargez ou visualisez les rÃ©sultats** : Consultez les rÃ©sultats directement dans l'application ou tÃ©lÃ©chargez-les dans le format de votre choix (CSV, JSON, TXT, HTML).\n\nCette application est conÃ§ue pour Ãªtre simple et intuitive ğŸ¯, tout en offrant des capacitÃ©s d'analyse puissantes pour rÃ©pondre aux besoins des professionnels du droit.\n\nBonne utilisation ! ğŸ’¼âœ¨"

fr_text:
  expander:
    _target_: streamlit.expander
    label: "ğŸ“ **Droit franÃ§ais dÃ©jÃ  traitÃ©**"
    expanded: False

  show_content:
    _target_: streamlit.checkbox
    label: "Afficher le contenu"

eu_text:
  expander:
    _target_: streamlit.expander
    label: "ğŸ¢ **Droit europÃ©en dÃ©jÃ  traitÃ©**"
    expanded: False

  show_content:
    _target_: streamlit.checkbox
    label: "Afficher le contenu"