summary_eu:
  download_docx:
    _target_: streamlit.download_button
    label: "ğŸ“¥ TÃ©lÃ©charger au format ```.docx```"
    file_name: "clustering.docx"

  confirm_run:
    _target_: streamlit.checkbox
    label: "ğŸ”¥ GÃ©nÃ©rer le rÃ©sumÃ©"
    key: "confirm_run_summary"
    value: false
  
  warning_computation_cost:
    _target_: streamlit.markdown
    body: "âš ï¸ **Attention :** Cette opÃ©ration peut prendre du temps en fonction de la taille du texte et du nombre d'articles Ã  transposer. En fonction de l'API choisie pour utiliser les LLMs, des coÃ»ts supplÃ©mentaires peuvent Ã©galement s'appliquer."

impact_analysis_of_eu_on_fr:
  download_html:
    _target_: streamlit.download_button
    label: "ğŸ“¥ TÃ©lÃ©charger au format ```.html```"
    file_name: "impact_analysis.html"

transposition_table:
  download_docx:
    _target_: streamlit.download_button
    label: "ğŸ“¥ TÃ©lÃ©charger au format ```.docx```"
    file_name: "tableau_de_transpo.docx"

  run_impact_analysis_first:
    _target_: streamlit.markdown
    body: "ğŸš¨ **Veuillez d'abord lancer l'analyse d'impact avant de gÃ©nÃ©rer le tableau de transposition.**"

  confirm_run:
    _target_: streamlit.checkbox
    label: "ğŸ”¥ GÃ©nÃ©rer le tableau de transposition"
    key: "confirm_run_transposition_table"
    value: false
  
  warning_computation_cost:
    _target_: streamlit.markdown
    body: "âš ï¸ **Attention :** Cette opÃ©ration peut prendre du temps en fonction de la taille du texte et du nombre d'articles Ã  transposer. En fonction de l'API choisie pour utiliser les LLMs, des coÃ»ts supplÃ©mentaires peuvent Ã©galement s'appliquer."